const tech = [
	'3g',
	'4g',
	'5g',
	'ajoneuvot',
	'akut',
	'appgallery',
	'apple',
	'auto',
	'autot',
	'autotestit',
	'autouutiset',
	'autoyesterday',
	'digitalous',
	'esports',
	'fossiiliset',
	'google',
	'haittaohjelmat',
	'huawei',
	'ios',
	'ipad',
	'ipados',
	'iphone',
	'kamera',
	'kamerat',
	'kehittäjäversio',
	'kiintolevyt',
	'kuulokkeet',
	'langattomat kuulokkeet',
	'lektroniikka',
	'lga115x',
	'lga1200',
	'linux',
	'läppärit',
	'mac',
	'microsoft',
	'internet',
	'smartphone',
	'gear',
	'mobiili',
	'mobiilisovellukset',
	'mobiiliuutiset',
	'motorola',
	'oheislaitteet',
	'ohjelmistot',
	'onePlus',
	'pikaviestimet',
	'polkupyörät',
	'puettavat',
	'puohjelmat',
	'pöytätietokoneet',
	'samsung',
	'selaimet',
	'snapdragon',
	'sony',
	'sosiaalinen media',
	'sovellukset',
	'sovellukset ja palvelut',
	'sovelluskaupat',
	'sähköauto',
	'sähköautot',
	'sähkömoottori',
	'sähköpyörät',
	'tabletit',
	'teknologia',
	'tietokoneet',
	'tietotekniikkauutiset',
	'tietoturva',
	'varavirtalähteet',
	'verkkotekniikka',
	'viikon tekniikkauutiset',
	'watchos',
	'windows',
	'android',
	'xiaomi',
	'yksityisyys',
	'youtube',
	'phone',
	'firmware',
	'galaxy',
	'a51',
	'oled',
	'long term reviews',
	'gear / products',
	'gear / reviews',
	'gear / products / outdoor',
	'hacking',
	'twitter',
	'breach',
	'hacker',
	'social media',
	'compromise',
	'bitcoin',
	'hack',
	'tech news',
	'first drives',
	'car lists',
	'cars',
	'electric car',
	'electric vehicle',
	'electric vehicles',
	'bugatti',
	'prices',
	'gm',
	'chevrolet',
	'suv',
	'mclaren',
	'mercedes',
	'amg',
	'maserati',
	'rivian',
	'fiat',
	'vw',
	'ford',
	'toyota',
	'bmw',
	'audi',
	'tesla',
	'scoops',
	'new cars',
	'chargers',
	'hybrids',
	'ev',
	'transportation',
	'reports',
	'galleries',
	'tiktok',
	'ban',
	'classic cars'
];

const entertainment = [
	'toimintapelit',
	'ajopelit',
	'cs:go',
	'csgo',
	'elokuva-arvostelut',
	'elokuvat',
	'elokuvauutiset',
	'ennakkokuuntelut',
	'folk',
	'hardcore',
	'hbo',
	'horoskooppi',
	'indie',
	'indiepelit',
	'kauhupelit',
	'metal',
	'musiikki',
	'musiikkivideo',
	'peli',
	'peli-viihde',
	'peliarvostelut',
	'pelikulttuuri',
	'pelimusiikki',
	'pelit',
	'pelitrailerit',
	'peliuutiset',
	'podcast',
	'pop',
	'post-hardcore / metalcore',
	'punk',
	'rock',
	'sarjat',
	'seikkailu- ja roolipelit',
	'tasohyppelyt',
	'tv & elokuvat',
	'tv-ja-leffat',
	'uuden musiikin julkaisut',
	'verkkopelit',
	'viihde',
	'viihdeuutiset',
	'yle areena'
];

const sport = [
	'aika-ajot',
	'amerikkalainen jalkapallo',
	'ammattilaiskoripallo',
	'ammattiurheilu',
	'ampumahiihto',
	'autourheilu',
	'bundesliiga',
	'englannin valioliiga',
	'eurocupit',
	'eurooppa-liiga',
	'eurosarjat',
	'f1',
	'fiba',
	'formula 1',
	'formula 1 -kuljettaja',
	'formula 1 -tallit',
	'golf',
	'jalkapallo',
	'jatkoaika (urheilu)',
	'joukkueurheilu',
	'jääkiekko',
	'jääkiekon miesten sm-liiga',
	'keihäänheitto',
	'khl',
	'koripallo',
	'la liga',
	'lentopallo',
	'liiga',
	'maailmancupit',
	'maajoukkueet',
	'maajoukkuekoripallo',
	'maaottelut',
	'major league soccer',
	'manchester united',
	'mestarien liiga',
	'miesten golf',
	'miesten jääkiekko',
	'miesten superpesis',
	'moottoripyöräily',
	'moottoripyöräurheilu',
	'motocross',
	'muut lajit',
	'muut sarjat',
	'naisurheilu',
	'nba',
	'nfl',
	'nhl',
	'nla',
	'olympialaiset',
	'pesäpallo',
	'pöytätennis',
	'ralli',
	'rata-autoilu',
	'ravivihjeet',
	'real madrid',
	'salibandy',
	'seitsenottelu',
	'serie a',
	'sm-liiga',
	'susijengi',
	'talviurheilu',
	'timanttiliiga',
	'uefa',
	'urheilu',
	'urheiluennätykset',
	'urheiluvalmennus',
	'valioliiga',
	'yleisurheilu'
];

module.exports = { tech, entertainment, sport };
