const tech = [
	'mobiili',
	'mobiiliuutiset',
	'tietotekniikkauutiset',
	'viikon tekniikkauutiset',
	'lga115x',
	'lga1200',
	'apple',
	'onePlus',
	'xiaomi',
	'motorola',
	'huawei',
	'samsung',
	'google',
	'microsoft',
	'windows',
	'linux',
	'sovellukset',
	'puettavat',
	'mac',
	'ios',
	'ipad',
	'ipados',
	'iphone',
	'google',
	'langattomat kuulokkeet',
	'kuulokkeet',
	'kamerat',
	'kamera',
	'youtube',
	'ajoneuvot',
	'ohjelmistot',
	'puohjelmat',
	'kiintolevyt',
	'pikaviestimet',
	'sovellukset ja palvelut',
	'läppärit',
	'pöytätietokoneet',
	'oheislaitteet',
	'varavirtalähteet',
	'tietoturva',
	'yksityisyys',
	'tietoturva',
	'selaimet',
	'autot',
	'auto',
	'sähkömoottori',
	'sähköpyörät',
	'polkupyörät',
	'sähköautot',
	'watchos',
	'sähköauto',
	'autotestit',
	'autouutiset',
	'tabletit',
	'lektroniikka',
	'digitalous',
	'mobiilisovellukset',
	'sosiaalinen media',
	'tietokoneet',
	'appgallery',
	'akut',
	'teknologia',
	'autoyesterday',
	'sony',
	'snapdragon',
	'4g',
	'5g',
	'kehittäjäversio'
];

module.exports = tech;
